- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
Replace all references to the old name, and remove the old mount points from orbit that were used for the submodules. It is now possible to properly build the repo again.
> 'syzygy' => 'singularity'

- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
Using the more verbose syntax for mounts and ports makes the compose files slightly longer, but splitting the specifications onto multiple lines of clear key/value pairs allows the compose to be self documenting and will make future changes easier by making merge conflicts easier to resolve since git is only smart enough to handle context in the form of full lines.
Depends on #23
> Cleanup compose files

- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
- orbit/Containerfile
By passing the value as an environment variable in the compose file it trashes the cache of all layers because that environment variable has to be set for all commands in all layers and could affect their behavior. This forces the builder to re-run everything including installing packages, building pip wheels etc. Since there are only two values, it isn't so bad -- once you have built with each at least once you will have a cache of both, but there is no reason to have two versions of each layer in the cache when really we only want to have it apply to the runtime environment. Passing the value as a build arg instead allows it to interact more carefully with the cache. Layers before the arg is mentioned in the Containerfile are blissfully unaware of it and because we really only want it …
> orbit: switch production/dev toggle from environment to ARG

- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
This is a nice step towards being able to run the code in the containers as a non root user for added security
> Use unprivileged ports within containers

- extenginx/nginx.conf.template
putting the `return` directive at the top level means that all processing immediately stops (including location directives), so as written, it was impossible to actually add snippets to the http server that do anything.
Moving the return statment into a `location /` block will allow it to continue to function as a fallback, but allows more specific overrides to be provided with additional location blocks in included snippets.
> extenginx: Fix redirect to https port

- extenginx/Containerfile
- orbit/Containerfile
Places where we use `\` to spread a command or string of commands across multiple lines should have a trailing line that does nothing so that all the real lines can look the same (i.e. all with \ or && \) so that future commit diffs can be tidy.
If you ever have to add something to the end of one of these improperly terminated lists, you will need to edit the previous last entry line and ruin its git blame with useless noise.
By creating this commit, I am creating such useless noise, but by doing it in a refactor commit that has no effect on behavior, I hope to help whoever comes across this while blaming to know they can skip it. This is not the commit you are looking for :)
Single commands whose arguments are spread can just have `;` on the last line, and pipelines separated by `&&` can …
> Containerfiles: cleanup \ multi-line continuations to normalize last entry

- extenginx/Containerfile
- extenginx/include.d/stream/README.md
- extenginx/nginx.conf.template
Cleaning some stuff up and adding new features.
> Extenginx improvements

- orbit/db.py
- orbit/hyperspace.py
- orbit/init-db.sql
Lots of stuff in db.py is totally unused. Get rid of it to make switching to an ORM more painless.
> Remove unused db queries

- orbit/db.py
- orbit/hyperspace.py
- orbit/init-db.sql
Since we have found a solution for running more than one independent version of the infrastructure, we no longer need to support lfx/non lfx for the mail servers. Since 326c3d6 we have not done so, but the lfx field remains in the database and in several queries. This PR removes all references to it.
> Lfx cleanup

- orbit/warpdrive.sh
set CONTAINER to singularity_orbit_1 which is essentially invariant and set DOCKER to our more commonly used podman. The script works with the default environment and sudoless invocation when the dev instance is the target, and works on the production/staging when sudoed.
Perhaps we should remove the CONTAINER env var entirely as I can't see how it would reasonably vary.
> orbit: warpdrive: use sane defaults for env vars

- tcp_server/tcp_server.c
Only signals that pid 1 has explicitly defined handlers for can be sent to pid 1 (including the first process in a container). For smtp and pop this is an instance of tcp_server. Since tcp_server does not define a handler for SIGTERM, the signal is ignored when tcp_server is acting as the init process of the container. Fixes #50
> tcp_server: specify handler for SIGTERM so it is not ignored

- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
- nginx_snippets/http/00-mail_auth.conf
- nginx_snippets/server_https/01-orbit-paths.conf
- nginx_snippets/stream/00-pop-proxy.conf
- nginx_snippets/stream/01-smtp-proxy.conf
The backend containers do not need to have exposed ports on the host when nginx can instead just connect directly to them. The prior state of the art was necessitated primarily by the kludge for mail auth where having one hostname to resolve (the host instead of pop/smtp containers) made things more palatable.
The backend containers also do not need to be able to communicate with each other, only with nginx. Using networks can allows for this sort of isolation.
> Remove host port mappings for backend containers and isolate them with networks

- orbit/test-style.sh
- test.sh
Some small tweaks and fixes to the test.sh script
> Test fixup

- container-compose-dev.yml
- container-compose-staging.yml
- container-compose.yml
- extenginx/Containerfile
- pop/Containerfile
- smtp/Containerfile
docker doesn't like additional contexts that contain capital letters so if we want compatibility we need to make this minor refactor.
> rename additional contexts to use all lowercase

- extenginx/create_dev_keys.sh
- orbit/test-style.sh
- orbit/warpdrive.sh
- script-lint.sh
- test.sh
substantial cleanup / refactor of tests to make them more useful.
Fixes: #56
> Test improvements

- container-compose.yml
turns out I was using the wrong syntax for setting selinux on a bind mount verbosely. There is a corresponding fixup commit pushed to kdlp-devel in the podman compose fork.
> container compose: fix selinux for bind mount

- container-compose-dev.yml
- orbit/.dockerignore
- orbit/Containerfile
- orbit/README.md
- orbit/config.py
- orbit/dev-requirements.txt
- orbit/hyperspace.py
- orbit/radius.ini
- orbit/radius.py
- orbit/requirements.txt
- orbit/warpdrive.sh
- submatrix/Containerfile
- test.sh
A bunch of changes that occurred to me as I had to wade through most of the code in orbit in order to switch to the ORM. Depends on #89.
> Orbit spring cleaning

- smtp/Containerfile
- smtp/smtp.c
using multiple folders for submissions logs was really an artifact of the unix permissions approach to mail access control. Since we are moving away from that, we can remove this complexity and make the SMTP server more straightfoward.
> Smtp cleanup

- container-compose.yml
- denis/Containerfile
- denis/db.py
- denis/submit.py
- orbit/Containerfile
- orbit/header.html
- orbit/radius.py
- watchtower/.dockerignore
- watchtower/watcher.c
Fixes: #94
Fixes: #65 
Fixes: #13
> Submission dashboard

- smtp/smtp.c
This PR overhauls how unique IDs are generated by the smtp program to make them more useful.
Instead of consisting of decimal values separated with periods, a fixed width hexadecimal format is adopted for easier parsing. The sub-values within the id are reordered so that the timestamp comes first followed by the pid followed by the sequence number so that sorting the values lexicographically produces a nice and sane ordering, and the timestamp is fetched once and cached at startup so that all ids generated by a given process will differ only in their sequence number.
The generic "sequence number" concept is split into a session number and then a unique id number within that session where sessions correspond to complete transactions from one user between logging in and executing `RSET` or …
> Improve Smtp Id Strings

- pop/init_journal.c
In line 84, the variable in strlen() should be ptr, not buf My computer could not pass the test with the bug.
After fixing the bug, my computer can pass the test.
> pop: fixed a bug in init_journal.c

- nginx_snippets/server_https/01-error-pages.conf
- submatrix/Containerfile
- submatrix/start.sh
This branch contains fixes for two regressions in singularity functionality.
1) new builds of the submatrix container fail because of an update to the python version in alpine
2) navigating within the cgit generated pages consistently logs the user out.
Fixes: #115
> Regressions

- README.md
- denis/submit.py
- orbit/hyperspace.py
- orbit/radius.py
- pop/restrict_access.c
- smtp/smtp.c
Fixes #108
Fixes #114
Fixes #120
Fixes #122
Fixes #128
Fixes #130
> Fixing Good first issues

- pop/init_journal.c
The `init_journal` program recreates the journal every time it is run. It does this by reading all the mail files from the mail folder and putting them into a new file and then atomically swapping that file for the old one.
Unfortunately the order that dirents are retrieved from a folder is not deterministic so the order that the email ends up in the journal can vary from one run to the next (especially if new items are added).
This interacts poorly with the assumption that access restriction can consist of just limiting the maximum extant of the journal file that a given user can access because the email will appear within the journal chronologically.
In order to fix this issue, a temporary solution is just to sort all the emails within the journal as the file names will …
> Fix Incorrect Mail Journalling

- denis/db.py
- denis/initial.py
> Record peer review assignments in database

- mailman/submit.py
Fixes #134
I chose to include the cover letter at the beginning of the git log as including it at the end would involve two different scenarios where we'd have to check for a missing cover letter: if the patches fail for some reason or if the patches all apply successfully. The patches could fail if what we call `cover_letter` isn't actually a cover letter, so we can avoid that scenario altogether by checking at the beginning.
> mailman: check for cover letter

- denis/configure.py
- denis/db.py
- denis/peer_review.py
- denis/start.py
> Add peer review to denis

- mailman/patchset.py
- mailman/submit.py
More refactoring is needed but this is a first step.
Fixes #146
> mailman: split patchset handling into separate file

- orbit/start.sh
using exec in the shell script will make uwsgi become pid 1 again which means that it can handle sigterm properly. The memcached daemon that is running in the background will be unceremoniously killed off when uwsgi exits, but this is not a problem because it (being a ram only cache) does not have persistent state.
> orbit: start.sh: use exec to make shutdown work correctly again

- .gitignore
- cgit_repos/cgitrepos
- container-compose.yml
- git/Containerfile
- git/admin.sh
- git/cgi-bin/git-receive-pack
- git/create-repo.sh
- git/gitconfig
- git/hooks/post-update
- git/setup-repo.sh
- orbit/Containerfile
- orbit/cgitrc
- script-lint.sh
A new container manages the class git repos.
They are initialized with a copy of singularity and a copy of any other bare repos stored in a new `docs` like folder called `repos`, and stored in a volume for persistence.
It has a warpdrive like script that allows adding new repos on the fly and runs an http server with a port mapped to the host that can accept pushes to the repos so they can be synced to publish new content as the semester progresses.
CGIT now pulls its repo data from this container's volume in a readonly fashion to publish the repos (behind auth) for students to clone.
> Add support for dynamic class git repos

- container-compose.yml
- mailman/Containerfile
- mailman/db.py
- mailman/submit.py
- orbit/radius.py
- Remove dependency on hard coded list of assignments
- Include peer reviews in dashboard log
> Dashboard Improvements

- denis/db.py
- denis/initial.py
the assignment field in the submissions table no longer exists having been replaced by recipient to accomodate peer reviews.
Fixes: 60d73a7 ("mailman: unify all submissions under common table for dashboard")
> denis: initial: update query to reflect new schema

- orbit/header.html
kinda nice
also considered making the whole div link to the page but it's a bit awkward.
We could also add "KDLP home" and "Course home" to the navbar but this PR is here to get the convo rolling
> orbit: logo link to kdlp.underground.software

- container-compose.yml
- mailman/db.py
- mailman/submit.py
- nginx_snippets/server_https/00-orbit-paths.conf
- orbit/Containerfile
- orbit/db.py
- orbit/header.html
- orbit/radius.py
After one year, we have finally surpassed what we had for a dashboard
> Dashboard overhaul

- mailman/patchset.py
- mailman/submit.py
Various small changes to mailman to improve the output and make it more robust
> Mailman Tweaks

- README.md
Updated README to replace 'flake8' installation instruction with 'python3-flake8' for improved compatibility and clarity.
> README.md flake8 fix

- orbit/Containerfile
Added a trailing && to orbit/Containerfile to prevent the colon on the next line from being interpreted as an argument to ./db.py
Addresses issue #154
> Add missing && to orbit/Containerfile

- orbit/header.html
We moved this content from ILKD_course_materials to kdlp.underground.software so we no longer retrieve this from the docs directory. Instead, we load it from our main website.
This also slightly simplifies deployment issues involving permissions errors when requesting static content.
> orbit: use asbolute static asset/image links

- container-compose.yml
- nginx_snippets/server_https/00-orbit-paths.conf
- orbit/radius.py
serve a Fedora 41 based Containefile from /Containerfile to enable easy student environment setup, including mostly completed .muttrc and .gitconfig files.
> orbit: serve a containerfile

- test.sh
turns out you can just not env -i and it still does exactly what you wanted. who knew
> test: remove env -i hostname bamboozling

- orbit/header.html
- orbit/radius.py
Fixes: #210
Fixes: #197 
edit: Get page titles from the markdown by reading the first line of the .md file, which is expected to be a header.
> radius: add page titles

- .flake8
- denis/initial.py
- denis/peer_review.py
- denis/start.py
- orbit/hyperspace.py
- orbit/radius.py
folks, we hate E501 don't we. it's no good. we love to have LONG LINES here, folks!!
> flake8: fix a spacing warning, disable some useless warnings

- orbit/db.py
Fixes #221. This fixes the issue where fullname was required even though the rest of the codebase assumes it can be NULL.
One limitation is that if the test script is run twice, it will still hit a UNIQUE constraint failed: user.student_id error, since test.sh tries to create a user with student_id = 1234, which already exists from the first run. This happens because the database persists between runs in the Podman volume. Clearing the volume before running the tests would prevent duplicate users from previous runs.
That said, this change should at least resolve the NOT NULL constraint failed: user.fullname issue!
> Fixes the issue where fullname was required 

- orbit/radius.py
> Orbit containerfile fixes

- .github/workflows/circumference-test-container.yaml
- Containerfile
- start.sh
There is no reason for circumference to be involved here, it just makes it easier to break CI if the two repos end up out of sync. We learned this lesson the last time we did something other than monorepo.
> CI: move code into singularity repo

- submatrix/Containerfile
- submatrix/start.sh
misc cleanups / opportunities for improvement discovered in submatrix while working on coverage code
> Submatrix fixes

- smtp/smtp.c
> limit email size

- mailman/patchset.py
When a student submits a corrupt patchset, only the cover letter makes it to the grading repository so if an instructor wishes to examine the patch they must dig into the containers and find the email file.
When mailman fails to apply a patch, the email patch file and all subsequent patchset in the patchset are committed to the repository as files and the resulting tag will contain these commits.
Fixes: #251
> mailman: commit raw patches when patchset is corrupt

- extenginx/Containerfile
Fixes: #242
Signed-off-by: Joel Savitz <joel@underground.software>
> extenginx: update self-signed key to use subjectAltName

- container-compose.yml
- denis/final.py
- denis/initial.py
- denis/peer_review.py
- denis/utilities.py
Since commit 22c9694 ("denis: add notes tied to initial and final submissions"), denis can now add notes to tagged submissions on the initial and final submission deadlines. We can build on this scaffolding to implement the first automated grading features. In this PR, I've included an initial set of three: automatic zero for corrupt or missing patchsets, DCO check, and subject tag format check. More to come.
Fixes https://github.com/underground-software/singularity/issues/207
Fixes https://github.com/underground-software/singularity/issues/110
Fixes https://github.com/underground-software/singularity/issues/262
> Denis enhanced

- denis/utilities.py
- mailman/db.py
- mailman/inspector.py
- mailman/patchset.py
- mailman/submit.py
- orbit/radius.py
Submissions.status has the same field name and refers to a different type of message so rename this one to better reflect its content.
Also update some variable names to reflect this change.
> denis,mailman,orbit: rename Gradable.{status => auto_feedback}

- git/admin.sh
- orbit/warpdrive.sh
- test.sh
We use podman around these parts
> treewide: s/DOCKER/PODMAN/g
